name: Build StreamDeck Plugin Distribution File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest #ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: SDP Dist
      id: sdpd
      uses: AlexHedley/streamdeckplugindistribution-test-action@v0.18
      with:
        plugin_path: src\com.elgato.counter.sdPlugin
